###########
# site.title

title:    'MineExpress'
subtitle: 'CS 175: Project in AI (in Minecraft) - Group 6 Herobrine'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
